"""
This script exports your trained TributeValueNetwork to ONNX format.
It is generated by AI
"""
import hashlib
import os
import torch
from ValueNetwork import TributeValueNetwork
from StateParser import NODE_DIM, GLOBAL_DIM

# 1. A dummy class that mimics a PyTorch Geometric Batch object.
# Only used to drive the unmodified base_model for verification below --
# the exported graph itself never sees a batch index (see ONNXWrapper).
class MockBatch:
    def __init__(self, x, batch, u):
        self.x = x
        self.batch = batch
        self.u = u

# 2. The ONNX Wrapper
# NOTE: this bypasses global_mean_pool entirely. torch_geometric's
# global_mean_pool lowers to a scatter-reduce in the ONNX graph, and ONNX
# opset 14 has no reduction attribute on ScatterElements (that arrived in
# opset 16/18) -- so the exporter silently fell back to replace semantics
# instead of averaging. At inference the bot always evaluates exactly one
# graph, so a plain per-node mean is correct and exports cleanly as
# ReduceMean.
class ONNXWrapper(torch.nn.Module):
    def __init__(self, base_model):
        super().__init__()
        self.node_encoder = base_model.node_encoder
        self.global_encoder = base_model.global_encoder
        self.evaluator = base_model.evaluator

    def forward(self, x, u):
        h = self.node_encoder(x)
        pooled = h.mean(dim=0, keepdim=True)  # -> ReduceMean, dynamic-safe
        g = self.global_encoder(u)
        return self.evaluator(torch.cat([pooled, g], dim=1))


def verify_export(base_model, onnx_filename):
    import onnxruntime as ort
    base_model.eval()
    sess = ort.InferenceSession(onnx_filename, providers=["CPUExecutionProvider"])
    worst = 0.0
    for n in [1, 2, 3, 5, 15, 16, 25, 40, 60]:
        x = torch.randn(n, NODE_DIM, dtype=torch.float32)
        u = torch.randn(1, GLOBAL_DIM, dtype=torch.float32)
        with torch.no_grad():
            ref = base_model(
                MockBatch(x, torch.zeros(n, dtype=torch.int64), u)
            ).item()
        got = float(sess.run(None, {
            "node_features": x.numpy(),
            "global_features": u.numpy(),
        })[0].reshape(-1)[0])
        d = abs(ref - got)
        worst = max(worst, d)
        print(f"  n={n:>3}  torch={ref:+.6f}  onnx={got:+.6f}  diff={d:.2e}")
    if worst >= 1e-5:
        raise RuntimeError(
            f"EXPORT VERIFICATION FAILED: max diff {worst:.3e} over {onnx_filename}")
    print(f"Export verified: max diff {worst:.3e}")


def export_model(checkpoint_path="best_model.pth", onnx_filename="DeepSetsValueNetwork.onnx"):
    print("=== EXPORTING SAKKIRINA TO ONNX ===")

    # Load your Grandmaster weights
    base_model = TributeValueNetwork(node_in_dim=NODE_DIM, global_in_dim=GLOBAL_DIM)
    base_model.load_state_dict(torch.load(checkpoint_path, map_location="cpu"))
    base_model.eval() # CRITICAL: Turn off dropout/batchnorm training modes

    wrapped_model = ONNXWrapper(base_model)

    # 3. Create Dummy Data to trace the graph
    num_nodes = 15

    # Dummy X: [15 nodes, NODE_DIM features]
    dummy_x = torch.randn(num_nodes, NODE_DIM, dtype=torch.float32)

    # Dummy U: [1 graph, GLOBAL_DIM global features]
    dummy_u = torch.randn(1, GLOBAL_DIM, dtype=torch.float32)

    torch.onnx.export(
        wrapped_model,
        (dummy_x, dummy_u),  # The tuple of raw tensor inputs -- no batch_mapping
        onnx_filename,
        export_params=True,
        opset_version=14,
        do_constant_folding=True,
        input_names=['node_features', 'global_features'],
        output_names=['win_probability'],
        # Dynamic axes are crucial! Every turn has a different number of cards (nodes).
        dynamic_axes={
            'node_features': {0: 'num_nodes'},
            'win_probability': {0: 'batch_size'}
        }
    )

    print(f"Exported to {onnx_filename}, verifying...")
    verify_export(base_model, onnx_filename)

    file_size = os.path.getsize(onnx_filename)
    with open(onnx_filename, "rb") as f:
        sha256 = hashlib.sha256(f.read()).hexdigest()
    print(f"{onnx_filename}: size={file_size} bytes, sha256={sha256}")

    print(f"✅ Successfully exported to {onnx_filename}!")

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Export a trained TributeValueNetwork checkpoint to ONNX.")
    parser.add_argument("--checkpoint", default="best_model.pth", help="Path to the .pth checkpoint to export")
    parser.add_argument("--out", default="DeepSetsValueNetwork.onnx", help="Output .onnx path")
    args = parser.parse_args()
    export_model(checkpoint_path=args.checkpoint, onnx_filename=args.out)
