"""
This script generates a C# file named CardDatabase.cs 
It contains a static dictionary mapping CardId enums to their corresponding effect vectors. 
Uses python card_db.py as the source for card effects.
This file is generated by AI
"""
import card_db

def build_csharp_file():
    print("Generating CardDatabase.cs...")
    
    with open("CardDatabase.cs", "w") as f:
        f.write("using System.Collections.Generic;\n")
        f.write("using ScriptsOfTribute;\n")
        f.write("using ScriptsOfTribute.Board;\n")
        f.write("using ScriptsOfTribute.Board.Cards;\n")
        f.write("using ScriptsOfTribute.Serializers;\n\n")
        f.write("namespace Bots\n{\n")
        f.write("    public static class CardDatabase\n    {\n")
        
        # Initialize the C# Dictionary
        f.write("        private static readonly Dictionary<CardId, float[]> Effects = new Dictionary<CardId, float[]>()\n")
        f.write("        {\n")
        
        # Loop through your Python dictionary and format it as C# syntax
        for card_key, effects_list in card_db.CARD_EFFECTS.items():
            # Clean up the key in case it was stored as a string or enum
            enum_name = str(card_key).replace("CardId.", "").strip()
            
            # Convert python floats/ints to C# float syntax (e.g., 1.0 -> 1.0f)
            float_strings = [f"{float(val)}f" for val in effects_list]
            array_string = ", ".join(float_strings)
            
            f.write(f"            {{ (CardId){enum_name}, new float[] {{ {array_string} }} }},\n")
            
        f.write("        };\n\n")
        
        # The lookup method that the FeatureExtractor class in DeepSetsCore.cs will call
        f.write("        public static float[] GetCardEffects(CardId cardId)\n")
        f.write("        {\n")
        f.write("            if (Effects.TryGetValue(cardId, out float[] effects))\n")
        f.write("                return effects;\n")
        f.write("\n            // Return a safe zero-vector if a card is somehow missing\n")
        # Ensure this matches the exact size of your effects array! (76 in our previous script)
        f.write(f"            return new float[{len(effects_list)}];\n") 
        f.write("        }\n")
        f.write("    }\n")
        f.write("}\n")
        
    print("✅ Successfully generated CardDatabase.cs!")

if __name__ == "__main__":
    build_csharp_file()